# Generated by Django 5.2.13 on 2026-04-21 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hunts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='completionrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hunt',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='hunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='hunts.hunt'),
        ),
        migrations.AddField(
            model_name='huntstory',
            name='hunt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='hunts.hunt'),
        ),
        migrations.AddField(
            model_name='team',
            name='hunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='hunts.hunt'),
        ),
        migrations.AddField(
            model_name='completionrecord',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hunts.team'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hunts.team'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('team', 'user')},
        ),
    ]
